export interface IVisitorExhib {
    id_vis: number,
    id: number,
    id_exhibition: number,
    fake_id: number,
    id_visitor: number,
    registered: number, 
    visited: number, 
    date_vis: string,
    date_reg: string,
    realname: string,
    referrer: string,
    utm_source: string,
    utm_medium: string,
    utm_campaign: string,
    utm_term: string,
    utm_content: string,
    new_visitor: string,

    cellphone: string,
    city: string, 
    email: string, 
    prizv: string, 
    regnum: number,
    potvid: string,
    name: string,
    namepovne: string,
    postaddreses: string,
    pobatkovi: string,
    gender: string,
    m_robotu: string,
    sferadij: string,
    posada: string,
    type: string,
    kompeten: string, 
    datawnesenny: string,
    datelastcor: string,
    ins_user: number,
    countryid: number,
    postindeks: string,
    regionid: number,
    address: string,
    telephon: string,
    rating: string
} 
 